# -*- coding: utf-8 -*-
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainGUIfile(object):
    def setupUi(self, MainGUIfile):
        MainGUIfile.setObjectName("MainGUIfile")
        MainGUIfile.resize(800, 600)
        self.pranGUI = QtWidgets.QLabel(MainGUIfile)
        self.pranGUI.setGeometry(QtCore.QRect(-30, -5, 831, 611))
        self.pranGUI.setText("")
        self.pranGUI.setPixmap(QtGui.QPixmap("IM1.gif"))
        self.pranGUI.setScaledContents(True)
        self.pranGUI.setObjectName("pranGUI")
        self.pushButton = QtWidgets.QPushButton(MainGUIfile)
        self.pushButton.setGeometry(QtCore.QRect(570, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2 = QtWidgets.QPushButton(MainGUIfile)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 550, 101, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(MainGUIfile)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 361, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("IM2.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(MainGUIfile)
        self.textBrowser.setGeometry(QtCore.QRect(390, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius: none; color:white; font-size: 20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(MainGUIfile)
        self.textBrowser_2.setGeometry(QtCore.QRect(570, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(16)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
"border-radius: none; color:white; font-size: 20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(MainGUIfile)
        QtCore.QMetaObject.connectSlotsByName(MainGUIfile)

    def retranslateUi(self, MainGUIfile):
        _translate = QtCore.QCoreApplication.translate
        MainGUIfile.setWindowTitle(_translate("MainGUIfile", "MainGUIfile"))
        self.pushButton.setText(_translate("MainGUIfile", "R U N"))
        self.pushButton_2.setText(_translate("MainGUIfile", "E X I T"))


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainGUIfile = QtWidgets.QWidget()
        ui = Ui_MainGUIfile()
        ui.setupUi(MainGUIfile)
        MainGUIfile.show()
        sys.exit(app.exec_())
